/** AI 调研问卷题目与存储键 */
window.SURVEY = {
  title: "聊聊你和 AI",
  subtitle: "匿名、轻松，大约 2 分钟。没有对错，想听真实感受。",
  storageKey: "ai-survey-responses-v1",
  questions: [
    {
      id: "role",
      type: "single",
      required: true,
      label: "你现在主要做什么？",
      options: ["临床", "医学事务", "市场准入", "销售", "研发", "其他"],
    },
    {
      id: "frequency",
      type: "single",
      required: true,
      label: "平时用 AI 多吗？",
      options: ["几乎每天", "每周都会用", "偶尔试试", "几乎不用"],
    },
    {
      id: "usage",
      type: "multi",
      required: true,
      label: "你主要拿它做什么？（可多选）",
      options: [
        "文献检索与阅读",
        "写材料与润色",
        "数据分析",
        "会议纪要",
        "知识问答",
        "其他",
      ],
    },
    {
      id: "satisfaction",
      type: "scale",
      required: true,
      label: "对现在用的 AI 工具，整体感觉如何？",
      min: 1,
      max: 5,
      minLabel: "不太行",
      maxLabel: "很喜欢",
    },
    {
      id: "painpoints",
      type: "multi",
      required: true,
      label: "最希望 AI 帮你扛掉哪类麻烦？（可多选）",
      options: [
        "信息过载",
        "重复性文书",
        "跨部门协作",
        "合规与引用准确",
        "多语言",
        "其他",
      ],
    },
    {
      id: "interest",
      type: "single",
      required: true,
      label: "如果有更贴合医学/药企场景的 AI，你会感兴趣吗？",
      options: ["非常感兴趣", "想先了解一下", "一般", "暂时不需要"],
    },
    {
      id: "concerns",
      type: "multi",
      required: true,
      label: "用起来你会顾虑什么？（可多选）",
      options: [
        "数据安全与隐私",
        "幻觉与准确性",
        "合规审核",
        "学习成本",
        "没什么顾虑",
      ],
    },
    {
      id: "wish",
      type: "text",
      required: false,
      label: "最想让下一个 AI 能力帮你做一件什么事？",
      placeholder: "选填，一句话就很好",
    },
  ],
};
